---
- hosts: all
  connection: local
  name: All information
  gather_facts: False
  vars_files:
    - vars/passwords.yml

  tasks:

  - include_tasks: utils_create_token.yml

  - name: Get All information
    redfish_info:
      category: Manager
      command: all
      baseuri: "{{ baseuri }}"
      auth_token: "{{ x_token }}"
    register: result

  - debug:
      var: result
