---
- hosts: all
  connection: local
  name: Log services
  gather_facts: False
  vars_files:
    - vars/passwords.yml

  tasks:

  - include_tasks: utils_create_token.yml

  - name: Get event log services
    uri:
      url: https://{{ baseuri }}/redfish/v1/Systems/system/LogServices/EventLog/Entries
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ x_token }}"
    register: result_eventlogs

  - debug:
      var: result_eventlogs
      verbosity: 2

  - set_fact:
      members: "{{result_eventlogs.json.Members}}"

  - debug:
      var: members
    when: result_eventlogs.json['Members@odata.count'] > 0

  - name: Get dump log services
    uri:
      url: https://{{ baseuri }}/redfish/v1/Systems/system/LogServices/Dump/Entries
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ x_token }}"
    register: result_dumplogs

  - debug:
      var: result_dumplogs
      verbosity: 2

  - set_fact:
      members: "{{result_dumplogs.json.Members}}"

  - debug:
      var: members
    when: result_dumplogs.json['Members@odata.count'] > 0
