---
- hosts: all
  connection: local
  name: Sessions
  gather_facts: False
  vars_files:
    - vars/passwords.yml

  tasks:

  - include_tasks: utils_create_token.yml

  - name: Get sessions
    redfish_info:
      category: Sessions
      command: GetSessions
      baseuri: "{{ baseuri }}"
      auth_token: "{{ x_token }}"
    register: result

  - ansible.builtin.debug:
      var: result.redfish_facts.session.entries
    when: result.redfish_facts.session.ret

