---
- hosts: all
  connection: local
  name: Memory Inventory
  gather_facts: False
  vars_files:
    - vars/passwords.yml

  tasks:

  - include_tasks: utils_create_token.yml

  - name: Get Memory Inventory
    redfish_info:
      category: Systems
      command: GetMemoryInventory
      baseuri: "{{ baseuri }}"
      auth_token: "{{ x_token }}"
    register: result

  - debug:
      var: result.redfish_facts.memory.entries
    when: result.redfish_facts.memory.ret
