---
- hosts: all
  connection: local
  name: Systems NIC inventory information
  gather_facts: False
  vars_files:
    - vars/passwords.yml

  tasks:

  - include_tasks: utils_create_token.yml

  - name: Get Systems NIC inventory information
    redfish_info:
      category: Systems
      command: GetNicInventory
      baseuri: "{{ baseuri }}"
      auth_token: "{{ x_token }}"
    register: result

  - debug:
      var: result
