---
- hosts: all
  connection: local
  name: Chassis Power report
  gather_facts: False
  vars_files:
    - vars/passwords.yml

  tasks:

  - include_tasks: utils_create_token.yml

  - name: Get Chassis Power
    redfish_info:
      category: Chassis
      command: all
      baseuri: "{{ baseuri }}"
      auth_token: "{{ x_token }}"
    register: result

  - ansible.builtin.debug:
      var: result.redfish_facts