---
- hosts: all
  connection: local
  name: List Users
  gather_facts: False
  vars_files:
    - vars/passwords.yml

  tasks:

  - include_tasks: utils_create_token.yml

  - name: List all users
    redfish_info:
      category: Accounts
      command: ListUsers
      baseuri: "{{ baseuri }}"
      auth_token: "{{ x_token }}"
    register: result

  - debug:
      var: result
