---
- hosts: all
  connection: local
  name: Boot information
  gather_facts: False
  vars_files:
    - vars/passwords.yml
  
  tasks:

  - include_tasks: utils_create_token.yml
  
  - name: Set one-time boot device to Cd
    community.general.redfish_command:
      category: Systems
      command: SetOneTimeBoot
      resource_id: system
      bootdevice: "Cd"
      baseuri: "{{ baseuri }}"
      auth_token: "{{ x_token }}"
