---
- hosts: all
  connection: local
  name: Chassis indicator led to blink
  gather_facts: False
  vars_files:
    - vars/passwords.yml
  
  tasks:

  - include_tasks: utils_create_token.yml
  
  - name: Set chassis indicator led to blink
    community.general.redfish_command:
      category: Chassis
      command: IndicatorLedBlink
      baseuri: "{{ baseuri }}"
      auth_token: "{{ x_token }}"
