---
- hosts: all
  connection: local
  name: Boot information
  gather_facts: False
  vars_files:
    - vars/passwords.yml
  
  tasks:

  - include_tasks: utils_create_token.yml

  - name: Set continuous boot device to Pxe
    community.general.redfish_command:
      category: Systems
      command: EnableContinuousBootOverride
      resource_id: system
      bootdevice: "Pxe"
      baseuri: "{{ baseuri }}"
      auth_token: "{{ x_token }}"
