---
  - name: Reboot BMC
    redfish_command:
      category: Manager
      command: GracefulRestart 
      baseuri: "{{baseuri}}"
      auth_token: "{{ x_token }}"
      resource_id: bmc
    register: result

  - debug:
      var: result
      verbosity: 2
