---

  - name: Create token from OpenBMC
    uri:
      url: https://{{ baseuri }}/redfish/v1/SessionService/Sessions
      method: POST
      validate_certs: no
      timeout: 30
      headers:
       Content-Type: "application/json"
      body_format: json
      body:
        UserName: "{{ username }}"
        Password: "{{ password }}"
      status_code: 201
    register: result
    until: result.status == 201
    retries: "6"
    delay: "10"

  - debug:
      var: result
      verbosity: 2

  - set_fact:
      x_token: "{{ result.x_auth_token }}"
  
  - debug:
      var: x_token
      verbosity: 2
