---
  - name: Orderly Restart system power
    redfish_command:
      category: Systems
      command: GracefulRestart
      baseuri: "{{baseuri}}"
      auth_token: "{{ x_token }}"
      resource_id: system
    register: result

  - debug:
      var: result
      verbosity: 2
