---
  - name: System power on
    redfish_command:
      category: Systems
      command: PowerOn
      baseuri: "{{baseuri}}"
      auth_token: "{{ x_token }}"
      resource_id: system
    register: result

  - debug:
      var: result
      verbosity: 2
