---
  - name: Orderly Shutdown system power gracefully
    redfish_command:
      category: Systems
      command: PowerGracefulShutdown
      baseuri: "{{baseuri}}"
      auth_token: "{{ x_token }}"
      resource_id: system
    register: result

  - debug:
      var: result
      verbosity: 2
