---
  - name: Wait until manager powered graceful restart
    block:
      - name: Set the retry counter
        set_fact:
          retry_power_graceful_restart_count: "{{ 0 if retry_power_graceful_restart_count is undefined else retry_power_graceful_restart_count|int + 1 }}"
        
      - debug:
          msg: "Pause {{ power_graceful_restart_countdown }}s while manager is powering graceful restart"

      - name: Pause while manager is powering graceful restart
        pause:
          seconds: "{{ power_graceful_restart_countdown }}"

      - name: Get Manager
        redfish_info:
          category: Manager
          baseuri: "{{ baseuri }}"
          auth_token: "{{ x_token }}"
          command: GetHealthReport
        register: result

      - fail:
          msg: "Manager graceful restarting in progress..."
        when: not result.redfish_facts is defined

      - debug:
          var: result.redfish_facts

      - debug:
          var: result.redfish_facts.health_report

      - debug:
          var: result.redfish_facts.health_report.entries

      - debug:
          var: result.redfish_facts.health_report.entries[0]

      - debug:
          msg: "entry: {{ result.redfish_facts.health_report.entries[0][1] }}"

      - debug:
          msg: "Status: {{ result.redfish_facts.health_report.entries[0][1].Manager.Status }}"

      - name: Current State
        set_fact:
          state: "{{ result.redfish_facts.health_report.entries[0][1].Manager.Status.State }}"
        when: result.redfish_facts is defined

      - debug:
          var: state

      - fail:
          msg: "Manager graceful restarting in progress..."
        when: not state == "Enabled"

    rescue:
      - fail:
          msg: Ended after {{ power_graceful_restart_maxretries }} retries
        when: retry_power_graceful_restart_count|int == power_graceful_restart_maxretries|int

      - name: Restarting Graceful Restart
        debug:
          msg: "Restarting On... 1 / {{ power_graceful_restart_maxretries }} "
        when: retry_power_graceful_restart_count|int == 1

      - name: Waiting for Graceful Restarting complete
        debug:
          msg: "Retrying check for power Graceful Restart complete... {{ retry_power_graceful_restart_count }} / {{ power_graceful_restart_maxretries }}  "
        when: retry_power_graceful_restart_count|int > 1

      - include_tasks: wait_until_manager_power_graceful_restart.yml
