---
  - name: Wait until manager is restarted
    block:
      - name: Set the retry counter
        set_fact:
          retry_power_force_restart_count: "{{ 0 if retry_power_force_restart_count is undefined else retry_power_force_restart_count|int + 1 }}"

      - debug:
          msg: "Pause {{ power_force_restart_countdown }}s while manager is powering forceful restart"       

      - name: Pause while manager is powering forceful restart
        pause:
          seconds: "{{ power_force_restart_countdown }}"

      - name: Get Manager
        redfish_info:
          category: Manager
          baseuri: "{{ baseuri }}"
          auth_token: "{{ x_token }}"
          command: GetHealthReport
        register: result

      - fail:
          msg: "Manager restarting in progress..."
        when: not result.redfish_facts is defined

      - debug:
          var: result.redfish_facts

      - debug:
          var: result.redfish_facts.health_report

      - debug:
          var: result.redfish_facts.health_report.entries

      - debug:
          var: result.redfish_facts.health_report.entries[0]

      - debug:
          msg: "entry: {{ result.redfish_facts.health_report.entries[0][1] }}"

      - debug:
          msg: "Status: {{ result.redfish_facts.health_report.entries[0][1].Manager.Status }}"

      - name: Current State
        set_fact:
          state: "{{ result.redfish_facts.health_report.entries[0][1].Manager.Status.State }}"
        when: result.redfish_facts is defined

      - debug:
          var: state

      - fail:
          msg: "Manager powering force restart in progress..."
        when: not state == "Enabled"

    rescue:
      - fail:
          msg: Ended after {{ power_force_restart_maxretries }} retries
        when: retry_power_force_restart_count|int == power_force_restart_maxretries|int

      - name: Powering Force Restart
        debug:
          msg: "Powering Force Restart... 1 / {{ power_force_restart_maxretries }} "
        when: retry_power_force_restart_count|int == 1

      - name: Waiting for Powering Force Restart complete
        debug:
          msg: "Retrying check for power force restart complete... {{ retry_power_force_restart_count }} / {{ power_force_restart_maxretries }}  "
        when: retry_power_force_restart_count|int > 1

      - include_tasks: wait_until_manager_power_force_restart.yml
