---
- hosts: all
  connection: local
  name: Check Host Power - Turn on
  gather_facts: False
  vars_files:
    - vars/external_vars.yml

  tasks:

  - include_tasks: utils_create_token.yml

  - include_tasks: utils_check_power_on.yml    

