---
- hosts: all
  connection: local
  name: Manage Orderly Host (Server) Power off 
  gather_facts: False
  vars_files:
    - vars/external_vars.yml

  tasks:

  - name: validate poweroff_countdown variable
    assert:
      that:
        - poweroff_countdown is defined
      fail_msg: "The variable poweroff_countdown is NOT defined in inventory (AWX) or vars/external_vars file (Ansible). See readme.md for more details."
      success_msg: "The variable poweroff_countdown is defined"
    run_once: true

  - name: validate poweroff_maxretries variable
    assert:
      that:
        - poweroff_maxretries is defined
      fail_msg: "The variable poweroff_maxretries is NOT defined in inventory (AWX) or vars/external_vars file (Ansible). See readme.md for more details."
      success_msg: "The variable poweroff_maxretries is defined"
    run_once: true

  - debug:
      msg: "poweroff_countdown is {{ poweroff_countdown }}s"
    when: poweroff_countdown is defined
    run_once: true

  - debug:
      msg: "poweroff_maxretries is {{ poweroff_maxretries }}"
    when: poweroff_maxretries is defined
    run_once: true

  - include_tasks: utils_create_token.yml

  - include_tasks: utils_orderly_power_off.yml

  - name: Retry until power off
    include_tasks: wait_until_success_power_off.yml   

  - include_tasks: utils_check_power_off.yml

